site_name: Desarrollo de Interfaces 2024/25

nav:
  - Inicio:
    - index.md
    - entorno.md
  - 0 Intro:
    - 00intro/01_electron_intro.md
    - 00intro/02_electron_firstapp.md
    - 00intro/021_actividad.md
    - 00intro/03_intro_interfaces.md
  - UD 1 JS:
    - 01js/index.md
    - 01js/01_sintaxis.md
    - 01js/011_actividades.md
    - 01js/02_funciones.md
    - 01js/03_objetos.md
    - 01js/04_arrays.md
    - 01js/05_callbacks_promesas.md
    - 01js/06_poo.md
    - 01js/061_actividades.md
    - 01js/062_example.md
  - UD 2 Node.js:
    - 02nodejs/index.md
    - 02nodejs/01_modules.md
    - 02nodejs/02_events.md
    - 02nodejs/03_servers_files.md
    - 02nodejs/ud2act01.md
  - UD 3 Electron:
    - 03electron/index.md
    - 03electron/01_intro.md
    - 03electron/02_dom.md
    - 03electron/03_events.md
    - 03electron/04_forms.md
    # - 03electron/05_ipc.md
    - 03electron/ud3_act1.md
    - 03electron/ud3_act2.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: light blue
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
  # logo: images/logo.png
  # favicon: images/favicon.ico

extra_css:
  - stylesheets/bs5_layout.css
  - stylesheets/custom.css

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      # emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - tags

